=head1 Common data in datatype constructors

Implement common data within datatypes (models single one-level inheritance)
this means that the base datatype definition can hold some data which all
constructors also hold though this could be expressed by all constructors
having a common first argument, this sugar would probably be useful. I'm
thinking of exceptions here. currently, exception handling needs three global
variables. Adding more information to exceptions will extend that number and
I'd like to keep it to 1 we could have a single object holding the exception
plus information (need to think about it).
