=head1 Projects

These pages contain some information on my personal projects. Not all my
projects also have a page here. For all public projects, visit
L<the git repositories|https://github.com/pippijn?tab=repositories>.

=over

=item L<Developer tools|devel/>

Tools for software development. Highly specialised to my needs.

=item L<Games|games/>

Computer games I play or used to play and now write stuff for.

=item L<Languages|lang/>

Programming languages and natural languages.

=item L<Network applications|net/>

Projects about communicating software.

=item L<Robotics|robotics/>

Autonomous systems projects.

=item L<Systems programming|system/>

Low level kernel projects.

=back


=head2 Continuous integration

Most of the projects I actively develop are hooked up to a continuous
integration system. Here are the projects' build statuses:

=over

=item L<< N<https://api.travis-ci.org/pippijn/aldor.png>|https://travis-ci.org/pippijn/aldor >> L<aldor|https://github.com/pippijn/aldor>

=item L<< N<https://api.travis-ci.org/pippijn/baselib.png>|https://travis-ci.org/pippijn/baselib >> L<baselib|https://github.com/pippijn/baselib>

=item L<< N<https://api.travis-ci.org/pippijn/codegen.png>|https://travis-ci.org/pippijn/codegen >> L<codegen|https://github.com/pippijn/codegen>

=item L<< N<https://api.travis-ci.org/pippijn/cparseparse.png>|https://travis-ci.org/pippijn/cparseparse >> L<cparseparse|https://github.com/pippijn/cparseparse>

=item L<< N<https://api.travis-ci.org/pippijn/cparser.png>|https://travis-ci.org/pippijn/cparser >> L<cparser|https://github.com/pippijn/cparser>

=item L<< N<https://api.travis-ci.org/pippijn/deliantra.png>|https://travis-ci.org/pippijn/deliantra >> L<deliantra|https://github.com/pippijn/deliantra>

=item L<< N<https://api.travis-ci.org/pippijn/dreml.png>|https://travis-ci.org/pippijn/dreml >> L<dreml|https://github.com/pippijn/dreml>

=item L<< N<https://api.travis-ci.org/pippijn/glr.png>|https://travis-ci.org/pippijn/glr >> L<glr|https://github.com/pippijn/glr>

=item L<< N<https://api.travis-ci.org/pippijn/gvoc.png>|https://travis-ci.org/pippijn/gvoc >> L<gvoc|https://github.com/pippijn/gvoc>

=item L<< N<https://api.travis-ci.org/pippijn/hm-infer.png>|https://travis-ci.org/pippijn/hm-infer >> L<hm-infer|https://github.com/pippijn/hm-infer>

=item L<< N<https://api.travis-ci.org/xinutec/irssi.png>|https://travis-ci.org/xinutec/irssi >> L<irssi|https://github.com/xinutec/irssi>

=item L<< N<https://api.travis-ci.org/pippijn/jmlc.png>|https://travis-ci.org/pippijn/jmlc >> L<jmlc|https://github.com/pippijn/jmlc>

=item L<< N<https://api.travis-ci.org/pippijn/lina-irc.png>|https://travis-ci.org/pippijn/lina-irc >> L<lina-irc|https://github.com/pippijn/lina-irc>

=item L<< N<https://api.travis-ci.org/pippijn/makequick.png>|https://travis-ci.org/pippijn/makequick >> L<makequick|https://github.com/pippijn/makequick>

=item L<< N<https://api.travis-ci.org/pippijn/menhir.png>|https://travis-ci.org/pippijn/menhir >> L<menhir|https://github.com/pippijn/menhir>

=item L<< N<https://api.travis-ci.org/pippijn/merr.png>|https://travis-ci.org/pippijn/merr >> L<merr|https://github.com/pippijn/merr>

=item L<< N<https://api.travis-ci.org/pippijn/mlspring.png>|https://travis-ci.org/pippijn/mlspring >> L<mlspring|https://github.com/pippijn/mlspring>

=item L<< N<https://api.travis-ci.org/pippijn/mlwidgets.png>|https://travis-ci.org/pippijn/mlwidgets >> L<mlwidgets|https://github.com/pippijn/mlwidgets>

=item L<< N<https://api.travis-ci.org/pippijn/obuild.png>|https://travis-ci.org/pippijn/obuild >> L<obuild|https://github.com/pippijn/obuild>

=item L<< N<https://api.travis-ci.org/pippijn/obuild-aldor.png>|https://travis-ci.org/pippijn/obuild-aldor >> L<obuild-aldor|https://github.com/pippijn/obuild-aldor>

=item L<< N<https://api.travis-ci.org/pippijn/oink-stack.png>|https://travis-ci.org/pippijn/oink >> L<oink-stack|https://github.com/pippijn/oink-stack>

=item L<< N<https://api.travis-ci.org/pippijn/pa_json.png>|https://travis-ci.org/pippijn/pa_json >> L<pa_json|https://github.com/pippijn/pa_json>

=item L<< N<https://api.travis-ci.org/pippijn/pa_monad_custom.png>|https://travis-ci.org/pippijn/pa_monad_custom >> L<pa_monad_custom|https://github.com/pippijn/pa_monad_custom>

=item L<< N<https://api.travis-ci.org/pippijn/pa_unpack.png>|https://travis-ci.org/pippijn/pa_unpack >> L<pa_unpack|https://github.com/pippijn/pa_unpack>

=item L<< N<https://api.travis-ci.org/pippijn/parmap.png>|https://travis-ci.org/pippijn/parmap >> L<parmap|https://github.com/pippijn/parmap>

=item L<< N<https://api.travis-ci.org/pippijn/re2ml.png>|https://travis-ci.org/pippijn/re2ml >> L<re2ml|https://github.com/pippijn/re2ml>

=item L<< N<https://api.travis-ci.org/danmey/treematch.png>|https://travis-ci.org/danmey/treematch >> L<treematch|https://github.com/danmey/treematch>

=item L<< N<https://api.travis-ci.org/pippijn/ucslib.png>|https://travis-ci.org/pippijn/ucslib >> L<ucslib|https://github.com/pippijn/ucslib>

=item L<< N<https://api.travis-ci.org/pippijn/yaccpp.png>|https://travis-ci.org/pippijn/yaccpp >> L<yaccpp|https://github.com/pippijn/yaccpp>

=back
