=head1 Why not to use PHP

PHP is a widely used web programming language. This does not necessarily mean
it is a good web programming language. I will not say anything about this.
Other people have done a better job on this.

=head2 Links

=over

=item L<PHP in contrast to Perl|http://tnx.nl/php>

=item L<PHP 5: not even close|http://tnx.nl/php5>

=item L<What I don't like about PHP|http://www.bitstorm.org/edwin/en/php/>

=back
