=head1 Licencing issues

Aldor is licenced under the L<Aldor Public Licence version 2|http://www.aldor.org/AldorPublicLicense2_0.html>.
I do not completely agree with this licence. Specifically point b) of the
fourth star really bites me and has kept me from publishing my changes for a
long time. It also keeps me from publishing more drastic changes. Publicly
available are only the changes that were strictly necessary in order to build
Aldor on Windows and make it work with all compile-time configuration options.

Currently, Rona, the general purpose library I created, is licenced under the
L<GNU Affero General Public Licence version 3|http://www.fsf.org/licensing/licenses/agpl-3.0.html>
or later. There is a special exception which applies to all header files which
allows them to be used as part of differently licenced works. This does not
mean that one can freely distribute the header files, it merely means macro
expansions, inline function expansions and template instantiations may be used
in compiled form within differently licenced works. The same holds for the
source files in this library. Differently licenced works may include a
binary-only distribution of the library.

The exception only holds for works that satisfy the conditions described in the
LICENCE file in the Aldor source root. Three more or less trivial header files
that are part of the Rona library but are vital for compiling aldor-generated C
code are BSD licenced. This allows the distribution of binary packages
including these header files.


=head2 Mailing list links

=over

=item L<Distributing Aldor|http://www.nabble.com/Distributing-Aldor-to19373429.html>

=item L<Licence question|http://www.nabble.com/Licence-question-to18943963.html>

=item L<Axiom for Aldor or Aldor for Axiom?|http://www.nabble.com/Axiom-for-Aldor-or-Aldor-for-Axiom--to12470616.html>

=back


=head2 Licences

=over

=item L<Aldor Public Licence version 2|http://www.aldor.org/AldorPublicLicense2_0.html>

=item L<GNU Affero General Public Licence version 3|http://www.fsf.org/licensing/licenses/agpl-3.0.html>

=item L<ISC Licence|http://www.opensource.org/licenses/isc-license.txt>

=back
